language: cpp

before_install:
  - git clone -b ocl-open-80 https://github.com/intel/opencl-clang opencl-clang


v8: &v8
  - llvm-8-tools
  - llvm-8-dev
  - libclang-8-dev
  - clang-8
  - clang-tools-8


matrix:
  include:
    - os: linux
      dist: xenial # Ubuntu 16.04
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages: *v8
    - os: linux
      dist: bionic # Ubuntu 18.04
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages: *v8

git:
  depth: 1

branches:
  only:
    - master

env:
  matrix:
    - BUILD_TYPE=Release

install:
  - export TARBALL1=SPIRV-LLVM-Translator-v8.0.1-2-linux-${BUILD_TYPE}.zip
  - wget https://github.com/KhronosGroup/SPIRV-LLVM-Translator/releases/download/v8.0.1-2/${TARBALL1} -O /tmp/${TARBALL1}
  - unzip /tmp/${TARBALL1} -d spirv-llvm-translator

compiler:
  - gcc

script:
  - mkdir opencl-clang/build && cd opencl-clang/build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DLLVM_NO_DEAD_STRIP=ON -DLLVMSPIRV_INCLUDED_IN_LLVM=OFF -DSPIRV_TRANSLATOR_DIR=../spirv-llvm-translator ..
  - sudo make install
  - cd ../..
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_FIND_DEBUG_MODE=ON -DIGC_PREFERRED_LLVM_VERSION=8 -DCCLANG_FROM_SYSTEM=TRUE ../IGC
  - make -j`nproc`