#=========================== begin_copyright_notice ============================
#
# Copyright (c) 2019-2021 Intel Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom
# the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
#
#============================ end_copyright_notice =============================

language: cpp
compiler: gcc

notifications:
    email:
        recipients: igc.git.maintainers@intel.com
    on_success: never # default: change
    on_failure: change # default: always

dist: focal
os: linux

matrix:
  include:
    - os: linux
      dist: focal # Ubuntu 20.04
      compiler: gcc
      env: LLVM_VER=10 BUILD_TYPE=Release
    - os: linux
      dist: focal # Ubuntu 20.04
      compiler: clang-10
      env: LLVM_VER=10 BUILD_TYPE=Release COMPILER_EXTRA="-DCMAKE_C_COMPILER=clang-10 -DCMAKE_CXX_COMPILER=clang++-10"

git:
  depth: false

branches:
  only:
    - master

script:
  - sudo apt-get update
  - sudo apt-get install flex bison libz-dev cmake

  - mkdir Old_IGC
  - cd Old_IGC
  - curl -s https://api.github.com/repos/intel/intel-graphics-compiler/releases/latest | grep browser_download_url | cut -d '"' -f 4 | wget -qi -
  - sudo dpkg -i *.deb
  - cd ..

  - wget https://apt.llvm.org/llvm.sh
  - chmod +x llvm.sh
  - sudo ./llvm.sh ${LLVM_VER}

  - git clone https://github.com/intel/vc-intrinsics ../vc-intrinsics
  - git clone -b llvm_release_100 https://github.com/KhronosGroup/SPIRV-LLVM-Translator ../llvm-project/llvm/projects/llvm-spirv
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DIGC_OPTION__LLVM_PREFERRED_VERSION=${LLVM_VER} -DCCLANG_FROM_SYSTEM=TRUE -DIGC_OPTION__LLVM_FROM_SYSTEM=True ${COMPILER_EXTRA} ../
  - make -j`nproc`
